name: nzdoc_maps_mobile
description: "NZ DOC maps mobile"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  json_annotation: ^4.9.0
  json_serializable: ^6.11.3
  flutter_map_location_marker: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/doc_icons/
